version: '3.7'

services:
  web:
    build: 
      context: ./project
      dockerfile: ../docker/dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./docker/.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sofomo_rekrutacja
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=sofomo_rekrutacja

volumes:
  postgres_data: